spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: ledger_user
    password: ledger_pass

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
